### ISSUE TITLE
Use date of upload instead of modification date to see if the file should be deleted

### ISSUE THREAD

**Issue by js94x** [nextcloud/files_retention#23]
### Steps to reproduce
1. upload a file with a modification date before 2014 using desktop client for windows
2. tag file with simple tag (e.g. "File") or use automated tagging 
3. set up a retention rule to delete files tagged with "File" after 10 days
4. run cron.php from command line

### Actual behaviour
The app uses modification date (could be years in the past) to decide whether the file should be deleted.

### Expected behaviour
The Retentition app should note the upload date in Nextcloud instead of the modification date that was transferred from the desktop client. After my research in the database table oc_filecache, I have not found a field for the upload date. 

Maybe you could use a hook in the retention app to perform a separate database entry which contains the date of the upload. If a extra field exists, you could decice in the preferences which date is used as criterium.

This background is as follows: I would like to use Nextcloud as a platform for temporary file exchange for friends, customers and others. Uploaded files should be deleted after x Days. But everytime I upload an older file from windows in the shared folder, the retention app would delete it after 24 hours at the latest.

### Server configuration
**Nextcloud version:** 11.0.1

**Comment by nickvergessen** [comment]
Yeah that is a bit unfortunate. I noticed this as well lately.

**Comment by js94x** [comment]
> Yeah that is a bit unfortunate. I noticed this as well lately.

Are there plans to integrate this feature into the retention app soon? 👍 

Currently I am using a cronjob with a find command on Linux which checks the _ctime_ of files in the filesystem. This variant works basically but has many pitfalls. For example:

- ctime changes when file is modified, renamed or moved
- the deletion process bypasses Nextcloud, so: 
1. Nextcloud does not recognize deletion immediately
2. If encryption is active the cronjob would become even more complex

**Comment by stekaa** [comment]
What do you think about using date values from table oc_activity? If a file is uploaded there is an record with timestamp and type "file_created". You can join tables oc_filecache and oc_activity by oc_filecache.fileid=oc_activity.object_id.

**Comment by nickvergessen** [comment]
No

**Comment by jkimalane** [comment]
The solution proposed by stekka seems quite plausible till db schema is altered to store upload timestamp in oc_filecache table. So I don't understand why did you responded with no.

**Comment by nickvergessen** [comment]
Because inter app dependencies are bad, activity is an app that may be disabled. file creation activities might be disabled, ...
Too many points of failure.

**Comment by jkimalane** [comment]
So is 'files' and yet files_retention uses data stored by it. So, what's the correct solution for this problem as obviously the core functionality of the files_retention app does not work correctly. So how can we fix this?

**Comment by nickvergessen** [comment]
files is a force enabled app and therefor different. Also the filecache table is not owned by the files app but the server itself.

**Comment by jkimalane** [comment]
So we have identified the show stopper but we haven't discussed any solution to overcome this. So as far I see, your solution seems to be a change or set of changes to the core itself.

**Comment by joopmartens** [comment]
I have placed a request for Nextcloud server to store the file upload datetimestamp into the database.
After this has been implemented the files_retention plugin can be changed to use this information for it's retention processing.

See: [https://github.com/nextcloud/server/issues/4403](https://github.com/nextcloud/server/issues/4403)

**Comment by nickvergessen** [comment]
This was already reported in https://github.com/nextcloud/server/issues/3572

**Comment by schiessle** [comment]
Should be solved with Nextcloud 18 and file retention 1.7.0

**Comment by critot** [comment]
Hi, 
the problem is still present in NC18.0.3 FR1.7.0

**Comment by tomdereub** [comment]
It seems that the server issue is solved, but the problem is still present in NC29.0.5 and FR1.17.2 ?
I don't see an "upload date" option in FR, and for example I've juste uploaded this file with thunderbird *cloud : 
![image](https://github.com/user-attachments/assets/9758ae41-b919-4751-bd9a-57bf58e7f225)
The original modified date is kept. So it'll be soon be deleted instead of being kept 6 month in this folder.

**Comment by rschneider1509** [comment]
i also still have this issue. 
i switched to "creation date" but is it the "upload date" or the original creation date? the later would also make no sense
